spring:
  threads:
    virtual:
      enabled: false

  application:
    name: vt
  datasource:
    url: jdbc:mysql://mysql:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      data-locations: [data.sql, insert_posts.sql]
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: create
